In [3]:
import numpy as np

# Cоздаем одномерный массив
a = np.array([1, 2, 3, 4])

# Вывод массива
print(a)

# Тип данных в массиве
print(a.dtype)

# Размерность массива
print(a.shape)

[1 2 3 4]
int64
(4,)


In [9]:
import numpy as np

# Cоздаем двумернный массив
b = np.array([[1, 22, 3], [5, 54, 2]])

# Выведем его, узанем тип переменной и узнаем размерность массива
print(b)
print(b.dtype)
print(b.shape)


[[ 1 22  3]
 [ 5 54  2]]
int64
(2, 3)


In [5]:
import numpy as np 

# Создаем матрицу состоящую из нулей и размерностью 3x5  
matrix0 = np.zeros((3, 5))

# Создаем две матрицы состоящую из единиц и размерностью 3x4 
matrix1 = np.ones((2, 3, 4))

# Вывод матриц
print(matrix0, matrix1, sep="\n")



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
import numpy as np

# Создаем массив благодаря функции arange от 3 до 9
ls = np.arange(3, 10)

# Вывод массива
print(ls)

# Получение отдельных элементво: вывод первого и последнего элемента
print(ls[0], ls[-1])

# Извлечение подмассива с помощью среза
print(ls[2:4])

In [13]:
import numpy as np 

# Создадим два одномерных массива
ls_1 = np.arange(1, 10)
ls_2 = np.arange(10, 19)

# Вывод поэлементного сложения
print(ls_1 + ls_2)

# Вывод поэлементного умножения
print(ls_1 * ls_2)

# Вывод средних занчений массивов
print(f"Средние величины массивов ls_1 = {np.mean(ls_1)} и ls_2 = {np.mean(ls_2)}")

# Вывод сумм массивов
print(f"Суммы массивов ls_1 = {np.sum(ls_1)} и ls_2 = {np.sum(ls_2)}")

[11 13 15 17 19 21 23 25 27]
[ 10  22  36  52  70  90 112 136 162]
Средние величины массивов ls_1 = 5.0 и ls_2 = 14.0
Суммы массивов ls_1 = 45 и ls_2 = 126


In [ ]:
import numpy as np 

# Eдиничная матрица 5×5
matrix1 = np.eye(5)

print("Eдиничная матрица 5×5")
print(matrix1)
print("Прибавляем к каждому занчению +50")
print(matrix1 + 50)

# Заполняем матрицу 3x4 случайными числами
matrix2 = np.random.rand(3, 4)
print("random.randn — случайная матрица 3×4")
print(matrix2)
print("Умножаем всю матрицу на 100")
print(matrix2 * 100)

# Выполняем сложение двух матриц
print("Суммируем матрицы")
matrix3 = np.array([[1, 2, 3], 
                    [1, 2, 3]])

matrix4 = np.array([[4, 6 , 7], 
                    [1, 8, 2]])
print(matrix3 + matrix4)


Eдиничная матрица 5×5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Прибавляем к каждому занчению +50
[[51. 50. 50. 50. 50.]
 [50. 51. 50. 50. 50.]
 [50. 50. 51. 50. 50.]
 [50. 50. 50. 51. 50.]
 [50. 50. 50. 50. 51.]]
random.randn — случайная матрица 3×4
[[0.0180163  0.14193356 0.79389228 0.75367919]
 [0.7989461  0.75504031 0.84988037 0.78257676]
 [0.47314722 0.81230488 0.6866934  0.81699144]]
Умножаем всю матрицу на 100
[[ 1.80163026 14.19335595 79.38922759 75.36791889]
 [79.89461048 75.50403066 84.98803745 78.25767642]
 [47.31472224 81.23048793 68.66934003 81.69914399]]
Суммируем матрицы
[[ 5  8 10]
 [ 2 10  5]]
