In [43]:
import numpy as np

# Cоздаем одномерный массив
a = np.array([1, 2, 3, 4])

# Вывод массива
print(a)

# Тип данных в массиве
print(type(a))

# Размерность массива
print(a.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [44]:
import numpy as np

# Cоздаем двумернный массив
b = np.array([[1, 22, 3], [5, 54, 2]])

# Выведем его, узанем тип переменной и узнаем размерность массива
print(b)
print(type(b))
print(b.shape)


[[ 1 22  3]
 [ 5 54  2]]
<class 'numpy.ndarray'>
(2, 3)


In [45]:
import numpy as np 

# Создаем матрицу состоящую из нулей и размерностью 3x5  
matrix0 = np.zeros((3, 5))

# Создаем две матрицы состоящую из единиц и размерностью 3x4 
matrix1 = np.ones((2, 3, 4))

# Вывод матриц
print(matrix0, matrix1, sep="\n")



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [46]:
import numpy as np

# Создаем массив благодаря функции arange от 3 до 9
ls = np.arange(3, 10)

# Вывод массива
print(ls)

# Получение отдельных элементво: вывод первого и последнего элемента
print(ls[0], ls[-1])

# Извлечение подмассива с помощью среза
print(ls[2:4])

[3 4 5 6 7 8 9]
3 9
[5 6]


In [ ]:
import numpy as np 

# Создадим два одномерных массива
ls_1 = np.arange(1, 10)
ls_2 = np.arange(10, 19)

# Вывод поэлементного сложения
print(ls_1 + ls_2)

# Вывод поэлементного умножения
print(ls_1 * ls_2)

# Вывод средних занчений массивов
print(f"Средние величины массивов ls_1 = {np.mean(ls_1)} и ls_2 = {np.mean(ls_2)}")

# Вывод сумм массивов
print(f"Суммы массивов ls_1 = {np.sum(ls_1)} и ls_2 = {np.sum(ls_2)}")